version: "2"         # required to adjust maintainability checks
exclude_patterns:
  - "javacc-**/"
  - "**/javacc/lexer/NSISParserConstants.java"
  - "**/javacc/lexer/NSISParserTokenManager.java"
  - "**/javacc/lexer/ParseException.java"
  - "**/javacc/lexer/SimpleCharStream.java"
  - "**/javacc/lexer/Token.java"
  - "**/javacc/lexer/TokenMgrError.java"