before_install:
  - chmod +x StephenChamberlain/nsis4netbeans/javacc-5.0/bin/javacc
  - chmod +x StephenChamberlain/nsis4netbeans/javacc-6.0/bin/javacc
language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk7