/* Generated By:JavaCC: Do not edit this line. NSISParserConstants.java */
package uk.co.chamberlain.netbeans.nsis.javacc.lexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NSISParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 4;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int MULTI_LINE_FUNCTION = 9;
  /** RegularExpression Id. */
  int MULTI_LINE_SECTION = 12;
  /** RegularExpression Id. */
  int ABORT = 14;
  /** RegularExpression Id. */
  int ADDBRANDINGIMAGE = 15;
  /** RegularExpression Id. */
  int ADDSIZE = 16;
  /** RegularExpression Id. */
  int AUTOCLOSEWINDOW = 17;
  /** RegularExpression Id. */
  int BGFONT = 18;
  /** RegularExpression Id. */
  int BGGRADIENT = 19;
  /** RegularExpression Id. */
  int BRANDINGTEXT = 20;
  /** RegularExpression Id. */
  int BRINGTOFRONT = 21;
  /** RegularExpression Id. */
  int CALL = 22;
  /** RegularExpression Id. */
  int CALLINSTDLL = 23;
  /** RegularExpression Id. */
  int CAPTION = 24;
  /** RegularExpression Id. */
  int CHANGEUI = 25;
  /** RegularExpression Id. */
  int CLEARERRORS = 26;
  /** RegularExpression Id. */
  int COMPONENTTEXT = 27;
  /** RegularExpression Id. */
  int GETDLLVERSION = 28;
  /** RegularExpression Id. */
  int GETDLLVERSIONLOCAL = 29;
  /** RegularExpression Id. */
  int GETFILETIME = 30;
  /** RegularExpression Id. */
  int GETFILETIMELOCAL = 31;
  /** RegularExpression Id. */
  int COPYFILES = 32;
  /** RegularExpression Id. */
  int CRCCHECK = 33;
  /** RegularExpression Id. */
  int CREATEDIRECTORY = 34;
  /** RegularExpression Id. */
  int CREATEFONT = 35;
  /** RegularExpression Id. */
  int CREATESHORTCUT = 36;
  /** RegularExpression Id. */
  int SETDATABLOCKOPTIMIZE = 37;
  /** RegularExpression Id. */
  int DELETEINISEC = 38;
  /** RegularExpression Id. */
  int DELETEINISTR = 39;
  /** RegularExpression Id. */
  int DELETEREGKEY = 40;
  /** RegularExpression Id. */
  int DELETEREGVALUE = 41;
  /** RegularExpression Id. */
  int DELETE = 42;
  /** RegularExpression Id. */
  int DETAILPRINT = 43;
  /** RegularExpression Id. */
  int DIRTEXT = 44;
  /** RegularExpression Id. */
  int DIRSHOW = 45;
  /** RegularExpression Id. */
  int DIRVAR = 46;
  /** RegularExpression Id. */
  int DIRVERIFY = 47;
  /** RegularExpression Id. */
  int GETINSTDIRERROR = 48;
  /** RegularExpression Id. */
  int ALLOWROOTDIRINSTALL = 49;
  /** RegularExpression Id. */
  int CHECKBITMAP = 50;
  /** RegularExpression Id. */
  int ENABLEWINDOW = 51;
  /** RegularExpression Id. */
  int ENUMREGKEY = 52;
  /** RegularExpression Id. */
  int ENUMREGVALUE = 53;
  /** RegularExpression Id. */
  int EXCH = 54;
  /** RegularExpression Id. */
  int EXEC = 55;
  /** RegularExpression Id. */
  int EXECWAIT = 56;
  /** RegularExpression Id. */
  int EXECSHELL = 57;
  /** RegularExpression Id. */
  int EXPANDENVSTRINGS = 58;
  /** RegularExpression Id. */
  int FINDWINDOW = 59;
  /** RegularExpression Id. */
  int FINDCLOSE = 60;
  /** RegularExpression Id. */
  int FINDFIRST = 61;
  /** RegularExpression Id. */
  int FINDNEXT = 62;
  /** RegularExpression Id. */
  int FILE = 63;
  /** RegularExpression Id. */
  int FILEBUFSIZE = 64;
  /** RegularExpression Id. */
  int FLUSHINI = 65;
  /** RegularExpression Id. */
  int RESERVEFILE = 66;
  /** RegularExpression Id. */
  int FILECLOSE = 67;
  /** RegularExpression Id. */
  int FILEERRORTEXT = 68;
  /** RegularExpression Id. */
  int FILEOPEN = 69;
  /** RegularExpression Id. */
  int FILEREAD = 70;
  /** RegularExpression Id. */
  int FILEWRITE = 71;
  /** RegularExpression Id. */
  int FILEREADBYTE = 72;
  /** RegularExpression Id. */
  int FILEWRITEBYTE = 73;
  /** RegularExpression Id. */
  int FILEREADUTF16LE = 74;
  /** RegularExpression Id. */
  int FILEWRITEUTF16LE = 75;
  /** RegularExpression Id. */
  int FILEREADWORD = 76;
  /** RegularExpression Id. */
  int FILEWRITEWORD = 77;
  /** RegularExpression Id. */
  int FILESEEK = 78;
  /** RegularExpression Id. */
  int FUNCTION = 79;
  /** RegularExpression Id. */
  int FUNCTIONEND = 80;
  /** RegularExpression Id. */
  int GETDLGITEM = 81;
  /** RegularExpression Id. */
  int GETFULLPATHNAME = 82;
  /** RegularExpression Id. */
  int GETTEMPFILENAME = 83;
  /** RegularExpression Id. */
  int HIDEWINDOW = 84;
  /** RegularExpression Id. */
  int ICON = 85;
  /** RegularExpression Id. */
  int IFABORT = 86;
  /** RegularExpression Id. */
  int IFERRORS = 87;
  /** RegularExpression Id. */
  int IFFILEEXISTS = 88;
  /** RegularExpression Id. */
  int IFREBOOTFLAG = 89;
  /** RegularExpression Id. */
  int IFSILENT = 90;
  /** RegularExpression Id. */
  int INSTALLDIRREGKEY = 91;
  /** RegularExpression Id. */
  int INSTALLCOLORS = 92;
  /** RegularExpression Id. */
  int INSTALLDIR = 93;
  /** RegularExpression Id. */
  int INSTPROGRESSFLAGS = 94;
  /** RegularExpression Id. */
  int INSTTYPE = 95;
  /** RegularExpression Id. */
  int INTOP = 96;
  /** RegularExpression Id. */
  int INTCMP = 97;
  /** RegularExpression Id. */
  int INTCMPU = 98;
  /** RegularExpression Id. */
  int INTFMT = 99;
  /** RegularExpression Id. */
  int ISWINDOW = 100;
  /** RegularExpression Id. */
  int GOTO = 101;
  /** RegularExpression Id. */
  int LANGSTRING = 102;
  /** RegularExpression Id. */
  int LANGSTRINGUP = 103;
  /** RegularExpression Id. */
  int LICENSEDATA = 104;
  /** RegularExpression Id. */
  int LICENSEFORCESELECTION = 105;
  /** RegularExpression Id. */
  int LICENSELANGSTRING = 106;
  /** RegularExpression Id. */
  int LICENSETEXT = 107;
  /** RegularExpression Id. */
  int LICENSEBKCOLOR = 108;
  /** RegularExpression Id. */
  int LOADLANGUAGEFILE = 109;
  /** RegularExpression Id. */
  int LOGSET = 110;
  /** RegularExpression Id. */
  int LOGTEXT = 111;
  /** RegularExpression Id. */
  int MESSAGEBOX = 112;
  /** RegularExpression Id. */
  int NOP = 113;
  /** RegularExpression Id. */
  int NAME = 114;
  /** RegularExpression Id. */
  int OUTFILE = 115;
  /** RegularExpression Id. */
  int PAGE = 116;
  /** RegularExpression Id. */
  int PAGECALLBACKS = 117;
  /** RegularExpression Id. */
  int PAGEEX = 118;
  /** RegularExpression Id. */
  int PAGEEXEND = 119;
  /** RegularExpression Id. */
  int POP = 120;
  /** RegularExpression Id. */
  int PUSH = 121;
  /** RegularExpression Id. */
  int QUIT = 122;
  /** RegularExpression Id. */
  int READINISTR = 123;
  /** RegularExpression Id. */
  int READREGDWORD = 124;
  /** RegularExpression Id. */
  int READREGSTR = 125;
  /** RegularExpression Id. */
  int READENVSTR = 126;
  /** RegularExpression Id. */
  int REBOOT = 127;
  /** RegularExpression Id. */
  int REGDLL = 128;
  /** RegularExpression Id. */
  int RENAME = 129;
  /** RegularExpression Id. */
  int RETURN = 130;
  /** RegularExpression Id. */
  int RMDIR = 131;
  /** RegularExpression Id. */
  int SECTION = 132;
  /** RegularExpression Id. */
  int SECTIONEND = 133;
  /** RegularExpression Id. */
  int SECTIONIN = 134;
  /** RegularExpression Id. */
  int SUBSECTION = 135;
  /** RegularExpression Id. */
  int SECTIONGROUP = 136;
  /** RegularExpression Id. */
  int SUBSECTIONEND = 137;
  /** RegularExpression Id. */
  int SECTIONGROUPEND = 138;
  /** RegularExpression Id. */
  int SEARCHPATH = 139;
  /** RegularExpression Id. */
  int SECTIONSETFLAGS = 140;
  /** RegularExpression Id. */
  int SECTIONGETFLAGS = 141;
  /** RegularExpression Id. */
  int SECTIONSETINSTTYPES = 142;
  /** RegularExpression Id. */
  int SECTIONGETINSTTYPES = 143;
  /** RegularExpression Id. */
  int SECTIONGETTEXT = 144;
  /** RegularExpression Id. */
  int SECTIONSETTEXT = 145;
  /** RegularExpression Id. */
  int SECTIONGETSIZE = 146;
  /** RegularExpression Id. */
  int SECTIONSETSIZE = 147;
  /** RegularExpression Id. */
  int GETCURINSTTYPE = 148;
  /** RegularExpression Id. */
  int SETCURINSTTYPE = 149;
  /** RegularExpression Id. */
  int INSTTYPESETTEXT = 150;
  /** RegularExpression Id. */
  int INSTTYPEGETTEXT = 151;
  /** RegularExpression Id. */
  int SENDMESSAGE = 152;
  /** RegularExpression Id. */
  int SETAUTOCLOSE = 153;
  /** RegularExpression Id. */
  int SETCTLCOLORS = 154;
  /** RegularExpression Id. */
  int SETBRANDINGIMAGE = 155;
  /** RegularExpression Id. */
  int SETCOMPRESS = 156;
  /** RegularExpression Id. */
  int SETCOMPRESSOR = 157;
  /** RegularExpression Id. */
  int SETCOMPRESSORDICTSIZE = 158;
  /** RegularExpression Id. */
  int SETCOMPRESSIONLEVEL = 159;
  /** RegularExpression Id. */
  int SETDATESAVE = 160;
  /** RegularExpression Id. */
  int SETDETAILSVIEW = 161;
  /** RegularExpression Id. */
  int SETDETAILSPRINT = 162;
  /** RegularExpression Id. */
  int SETERRORS = 163;
  /** RegularExpression Id. */
  int SETERRORLEVEL = 164;
  /** RegularExpression Id. */
  int GETERRORLEVEL = 165;
  /** RegularExpression Id. */
  int SETFILEATTRIBUTES = 166;
  /** RegularExpression Id. */
  int SETFONT = 167;
  /** RegularExpression Id. */
  int SETOUTPATH = 168;
  /** RegularExpression Id. */
  int SETOVERWRITE = 169;
  /** RegularExpression Id. */
  int SETPLUGINUNLOAD = 170;
  /** RegularExpression Id. */
  int SETREBOOTFLAG = 171;
  /** RegularExpression Id. */
  int SETREGVIEW = 172;
  /** RegularExpression Id. */
  int SETSHELLVARCONTEXT = 173;
  /** RegularExpression Id. */
  int SETSILENT = 174;
  /** RegularExpression Id. */
  int SHOWINSTDETAILS = 175;
  /** RegularExpression Id. */
  int SHOWUNINSTDETAILS = 176;
  /** RegularExpression Id. */
  int SHOWWINDOW = 177;
  /** RegularExpression Id. */
  int SILENTINSTALL = 178;
  /** RegularExpression Id. */
  int SILENTUNINSTALL = 179;
  /** RegularExpression Id. */
  int SLEEP = 180;
  /** RegularExpression Id. */
  int STRCMP = 181;
  /** RegularExpression Id. */
  int STRCMPS = 182;
  /** RegularExpression Id. */
  int STRCPY = 183;
  /** RegularExpression Id. */
  int UNSAFESTRCPY = 184;
  /** RegularExpression Id. */
  int STRLEN = 185;
  /** RegularExpression Id. */
  int SUBCAPTION = 186;
  /** RegularExpression Id. */
  int TARGET = 187;
  /** RegularExpression Id. */
  int CPU = 188;
  /** RegularExpression Id. */
  int UNICODE = 189;
  /** RegularExpression Id. */
  int UNINSTALLEXENAME = 190;
  /** RegularExpression Id. */
  int UNINSTALLCAPTION = 191;
  /** RegularExpression Id. */
  int UNINSTALLICON = 192;
  /** RegularExpression Id. */
  int UNINSTPAGE = 193;
  /** RegularExpression Id. */
  int UNINSTALLTEXT = 194;
  /** RegularExpression Id. */
  int UNINSTALLSUBCAPTION = 195;
  /** RegularExpression Id. */
  int UNREGDLL = 196;
  /** RegularExpression Id. */
  int WINDOWICON = 197;
  /** RegularExpression Id. */
  int WRITEINISTR = 198;
  /** RegularExpression Id. */
  int WRITEREGBIN = 199;
  /** RegularExpression Id. */
  int WRITEREGDWORD = 200;
  /** RegularExpression Id. */
  int WRITEREGSTR = 201;
  /** RegularExpression Id. */
  int WRITEREGEXPANDSTR = 202;
  /** RegularExpression Id. */
  int WRITEUNINSTALLER = 203;
  /** RegularExpression Id. */
  int PEDLLCHARACTERISTICS = 204;
  /** RegularExpression Id. */
  int PESUBSYSVER = 205;
  /** RegularExpression Id. */
  int XPSTYLE = 206;
  /** RegularExpression Id. */
  int REQUESTEXECUTIONLEVEL = 207;
  /** RegularExpression Id. */
  int MANIFESTDPIAWARE = 208;
  /** RegularExpression Id. */
  int MANIFESTSUPPORTEDOS = 209;
  /** RegularExpression Id. */
  int PACKHDR = 210;
  /** RegularExpression Id. */
  int FINALIZE = 211;
  /** RegularExpression Id. */
  int SYSTEM = 212;
  /** RegularExpression Id. */
  int EXECUTE = 213;
  /** RegularExpression Id. */
  int ADDINCLUDEDIR = 214;
  /** RegularExpression Id. */
  int INCLUDE = 215;
  /** RegularExpression Id. */
  int CD = 216;
  /** RegularExpression Id. */
  int IF = 217;
  /** RegularExpression Id. */
  int IFDEF = 218;
  /** RegularExpression Id. */
  int IFNDEF = 219;
  /** RegularExpression Id. */
  int ENDIF = 220;
  /** RegularExpression Id. */
  int DEFINE = 221;
  /** RegularExpression Id. */
  int UNDEF = 222;
  /** RegularExpression Id. */
  int ELSE = 223;
  /** RegularExpression Id. */
  int ECHO = 224;
  /** RegularExpression Id. */
  int WARNING = 225;
  /** RegularExpression Id. */
  int ERROR = 226;
  /** RegularExpression Id. */
  int VERBOSE = 227;
  /** RegularExpression Id. */
  int MACRO = 228;
  /** RegularExpression Id. */
  int MACROEND = 229;
  /** RegularExpression Id. */
  int MACROUNDEF = 230;
  /** RegularExpression Id. */
  int INSERTMACRO = 231;
  /** RegularExpression Id. */
  int IFMACRODEF = 232;
  /** RegularExpression Id. */
  int IFMACRONDEF = 233;
  /** RegularExpression Id. */
  int TEMPFILE = 234;
  /** RegularExpression Id. */
  int DELFILE = 235;
  /** RegularExpression Id. */
  int APPENDFILE = 236;
  /** RegularExpression Id. */
  int SEARCHPARSE = 237;
  /** RegularExpression Id. */
  int SEARCHREPLACE = 238;
  /** RegularExpression Id. */
  int MISCBUTTONTEXT = 239;
  /** RegularExpression Id. */
  int DETAILSBUTTONTEXT = 240;
  /** RegularExpression Id. */
  int UNINSTALLBUTTONTEXT = 241;
  /** RegularExpression Id. */
  int INSTALLBUTTONTEXT = 242;
  /** RegularExpression Id. */
  int SPACETEXTS = 243;
  /** RegularExpression Id. */
  int COMPLETEDTEXT = 244;
  /** RegularExpression Id. */
  int GETFUNCTIONADDRESS = 245;
  /** RegularExpression Id. */
  int GETLABELADDRESS = 246;
  /** RegularExpression Id. */
  int GETCURRENTADDRESS = 247;
  /** RegularExpression Id. */
  int ADDPLUGINDIR = 248;
  /** RegularExpression Id. */
  int INITPLUGINSDIR = 249;
  /** RegularExpression Id. */
  int ALLOWSKIPFILES = 250;
  /** RegularExpression Id. */
  int VAR = 251;
  /** RegularExpression Id. */
  int VIADDVERSIONKEY = 252;
  /** RegularExpression Id. */
  int VIPRODUCTVERSION = 253;
  /** RegularExpression Id. */
  int VIFILEVERSION = 254;
  /** RegularExpression Id. */
  int LOCKWINDOW = 255;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 256;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 257;
  /** RegularExpression Id. */
  int HEX_LITERAL = 258;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 259;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 260;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 261;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 262;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 263;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 264;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 265;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL_1 = 266;
  /** RegularExpression Id. */
  int STRING_LITERAL = 267;
  /** RegularExpression Id. */
  int IDENTIFIER = 268;
  /** RegularExpression Id. */
  int LETTER = 269;
  /** RegularExpression Id. */
  int PART_LETTER = 270;
  /** RegularExpression Id. */
  int LPAREN = 271;
  /** RegularExpression Id. */
  int RPAREN = 272;
  /** RegularExpression Id. */
  int LBRACE = 273;
  /** RegularExpression Id. */
  int RBRACE = 274;
  /** RegularExpression Id. */
  int LBRACKET = 275;
  /** RegularExpression Id. */
  int RBRACKET = 276;
  /** RegularExpression Id. */
  int COMMA = 277;
  /** RegularExpression Id. */
  int DOT = 278;
  /** RegularExpression Id. */
  int AT = 279;
  /** RegularExpression Id. */
  int ASSIGN = 280;
  /** RegularExpression Id. */
  int LT = 281;
  /** RegularExpression Id. */
  int BANG = 282;
  /** RegularExpression Id. */
  int TILDE = 283;
  /** RegularExpression Id. */
  int HOOK = 284;
  /** RegularExpression Id. */
  int COLON = 285;
  /** RegularExpression Id. */
  int EQ = 286;
  /** RegularExpression Id. */
  int LE = 287;
  /** RegularExpression Id. */
  int GE = 288;
  /** RegularExpression Id. */
  int NE = 289;
  /** RegularExpression Id. */
  int SC_OR = 290;
  /** RegularExpression Id. */
  int SC_AND = 291;
  /** RegularExpression Id. */
  int INCR = 292;
  /** RegularExpression Id. */
  int DECR = 293;
  /** RegularExpression Id. */
  int PLUS = 294;
  /** RegularExpression Id. */
  int MINUS = 295;
  /** RegularExpression Id. */
  int STAR = 296;
  /** RegularExpression Id. */
  int SLASH = 297;
  /** RegularExpression Id. */
  int BIT_AND = 298;
  /** RegularExpression Id. */
  int BIT_OR = 299;
  /** RegularExpression Id. */
  int XOR = 300;
  /** RegularExpression Id. */
  int REM = 301;
  /** RegularExpression Id. */
  int LSHIFT = 302;
  /** RegularExpression Id. */
  int PLUSASSIGN = 303;
  /** RegularExpression Id. */
  int MINUSASSIGN = 304;
  /** RegularExpression Id. */
  int STARASSIGN = 305;
  /** RegularExpression Id. */
  int SLASHASSIGN = 306;
  /** RegularExpression Id. */
  int ANDASSIGN = 307;
  /** RegularExpression Id. */
  int ORASSIGN = 308;
  /** RegularExpression Id. */
  int XORASSIGN = 309;
  /** RegularExpression Id. */
  int REMASSIGN = 310;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 311;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 312;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 313;
  /** RegularExpression Id. */
  int ELLIPSIS = 314;
  /** RegularExpression Id. */
  int UNEXPECTED_CHARACTER = 315;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_FUNCTION = 3;
  /** Lexical state. */
  int IN_MULTI_LINE_SECTION = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<token of kind 2>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 7>",
    "\"FUNCTION\"",
    "\"FUNCTIONEND\"",
    "<token of kind 10>",
    "\"SECTION\"",
    "\"SECTIONEND\"",
    "<token of kind 13>",
    "\"Abort\"",
    "\"AddBrandingImage\"",
    "\"AddSize\"",
    "\"AutoCloseWindow\"",
    "\"BGFont\"",
    "\"BGGradient\"",
    "\"BrandingText\"",
    "\"BringToFront \"",
    "\"Call\"",
    "\"CallInstDLL\"",
    "\"Caption\"",
    "\"ChangeUI\"",
    "\"ClearErrors \"",
    "\"ComponentText\"",
    "\"GetDLLVersion\"",
    "\"GetDLLVersionLocal\"",
    "\"GetFileTime\"",
    "\"GetFileTimeLocal\"",
    "\"CopyFiles\"",
    "\"CRCCheck\"",
    "\"CreateDirectory\"",
    "\"CreateFont\"",
    "\"CreateShortcut\"",
    "\"SetDatablockOptimize\"",
    "\"DeleteINISec\"",
    "\"DeleteINIStr\"",
    "\"DeleteRegKey\"",
    "\"DeleteRegValue\"",
    "\"Delete\"",
    "\"DetailPrint\"",
    "\"DirText\"",
    "\"DirShow\"",
    "\"DirVar\"",
    "\"DirVerify\"",
    "\"GetInstDirError\"",
    "\"AllowRootDirInstall\"",
    "\"CheckBitmap\"",
    "\"EnableWindow\"",
    "\"EnumRegKey\"",
    "\"EnumRegValue\"",
    "\"Exch\"",
    "\"Exec\"",
    "\"ExecWait\"",
    "\"ExecShell\"",
    "\"ExpandEnvStrings\"",
    "\"FindWindow\"",
    "\"FindClose\"",
    "\"FindFirst\"",
    "\"FindNext\"",
    "\"File\"",
    "\"FileBufSize\"",
    "\"FlushINI\"",
    "\"ReserveFile\"",
    "\"FileClose\"",
    "\"FileErrorText\"",
    "\"FileOpen\"",
    "\"FileRead\"",
    "\"FileWrite\"",
    "\"FileReadByte\"",
    "\"FileWriteByte\"",
    "\"FileReadUTF16LE\"",
    "\"FileWriteUTF16LE\"",
    "\"FileReadWord\"",
    "\"FileWriteWord\"",
    "\"FileSeek\"",
    "\"Function\"",
    "\"FunctionEnd \"",
    "\"GetDlgItem\"",
    "\"GetFullPathName\"",
    "\"GetTempFileName\"",
    "\"HideWindow\"",
    "\"Icon\"",
    "\"IfAbort\"",
    "\"IfErrors\"",
    "\"IfFileExists\"",
    "\"IfRebootFlag\"",
    "\"IfSilent\"",
    "\"InstallDirRegKey\"",
    "\"InstallColors\"",
    "\"InstallDir\"",
    "\"InstProgressFlags\"",
    "\"InstType\"",
    "\"IntOp\"",
    "\"IntCmp\"",
    "\"IntCmpU\"",
    "\"IntFmt\"",
    "\"IsWindow\"",
    "\"Goto\"",
    "\"LangString\"",
    "\"LangStringUP\"",
    "\"LicenseData\"",
    "\"LicenseForceSelection\"",
    "\"LicenseLangString\"",
    "\"LicenseText\"",
    "\"LicenseBkColor\"",
    "\"LoadLanguageFile\"",
    "\"LogSet\"",
    "\"LogText\"",
    "\"MessageBox\"",
    "\"Nop\"",
    "\"Name\"",
    "\"OutFile\"",
    "\"Page\"",
    "\"PageCallbacks\"",
    "\"PageEx\"",
    "\"PageExEnd\"",
    "\"Pop\"",
    "\"Push\"",
    "\"Quit\"",
    "\"ReadINIStr\"",
    "\"ReadRegDWORD\"",
    "\"ReadRegStr\"",
    "\"ReadEnvStr\"",
    "\"Reboot\"",
    "\"RegDLL\"",
    "\"Rename\"",
    "\"Return\"",
    "\"RMDir\"",
    "\"Section\"",
    "\"SectionEnd\"",
    "\"SectionIn\"",
    "\"SubSection\"",
    "\"SectionGroup\"",
    "\"SubSectionEnd\"",
    "\"SectionGroupEnd\"",
    "\"SearchPath\"",
    "\"SectionSetFlags\"",
    "\"SectionGetFlags\"",
    "\"SectionSetInstTypes\"",
    "\"SectionGetInstTypes\"",
    "\"SectionGetText\"",
    "\"SectionSetText\"",
    "\"SectionGetSize\"",
    "\"SectionSetSize\"",
    "\"GetCurInstType\"",
    "\"SetCurInstType\"",
    "\"InstTypeSetText\"",
    "\"InstTypeGetText\"",
    "\"SendMessage\"",
    "\"SetAutoClose\"",
    "\"SetCtlColors\"",
    "\"SetBrandingImage\"",
    "\"SetCompress\"",
    "\"SetCompressor\"",
    "\"SetCompressorDictSize\"",
    "\"SetCompressionLevel\"",
    "\"SetDateSave\"",
    "\"SetDetailsView\"",
    "\"SetDetailsPrint\"",
    "\"SetErrors\"",
    "\"SetErrorLevel\"",
    "\"GetErrorLevel\"",
    "\"SetFileAttributes\"",
    "\"SetFont\"",
    "\"SetOutPath\"",
    "\"SetOverwrite\"",
    "\"SetPluginUnload\"",
    "\"SetRebootFlag\"",
    "\"SetRegView\"",
    "\"SetShellVarContext\"",
    "\"SetSilent\"",
    "\"ShowInstDetails\"",
    "\"ShowUninstDetails\"",
    "\"ShowWindow\"",
    "\"SilentInstall\"",
    "\"SilentUnInstall\"",
    "\"Sleep\"",
    "\"StrCmp\"",
    "\"StrCmpS\"",
    "\"StrCpy\"",
    "\"UnsafeStrCpy\"",
    "\"StrLen\"",
    "\"SubCaption\"",
    "\"Target\"",
    "\"CPU\"",
    "\"Unicode\"",
    "\"UninstallExeName\"",
    "\"UninstallCaption\"",
    "\"UninstallIcon\"",
    "\"UninstPage\"",
    "\"UninstallText\"",
    "\"UninstallSubCaption\"",
    "\"UnRegDLL\"",
    "\"WindowIcon\"",
    "\"WriteINIStr\"",
    "\"WriteRegBin\"",
    "\"WriteRegDWORD\"",
    "\"WriteRegStr\"",
    "\"WriteRegExpandStr\"",
    "\"WriteUninstaller\"",
    "\"PEDllCharacteristics\"",
    "\"PESubsysVer\"",
    "\"XPStyle\"",
    "\"RequestExecutionLevel\"",
    "\"ManifestDPIAware\"",
    "\"ManifestSupportedOS\"",
    "\"!packhdr\"",
    "\"!finalize\"",
    "\"!system\"",
    "\"!execute\"",
    "\"!AddIncludeDir\"",
    "\"!include\"",
    "\"!cd\"",
    "\"!if\"",
    "\"!ifdef\"",
    "\"!ifndef\"",
    "\"!endif\"",
    "\"!define\"",
    "\"!undef\"",
    "\"!else\"",
    "\"!echo\"",
    "\"!warning\"",
    "\"!error\"",
    "\"!verbose\"",
    "\"!macro\"",
    "\"!macroend\"",
    "\"!macroundef\"",
    "\"!insertmacro\"",
    "\"!ifmacrodef\"",
    "\"!ifmacrondef\"",
    "\"!tempfile\"",
    "\"!delfile\"",
    "\"!appendfile\"",
    "\"!searchparse\"",
    "\"!searchreplace\"",
    "\"MiscButtonText\"",
    "\"DetailsButtonText\"",
    "\"UninstallButtonText\"",
    "\"InstallButtonText\"",
    "\"SpaceTexts\"",
    "\"CompletedText\"",
    "\"GetFunctionAddress\"",
    "\"GetLabelAddress\"",
    "\"GetCurrentAddress\"",
    "\"!AddPluginDir\"",
    "\"InitPluginsDir\"",
    "\"AllowSkipFiles\"",
    "\"Var\"",
    "\"VIAddVersionKey\"",
    "\"VIProductVersion\"",
    "\"VIFileVersion\"",
    "\"LockWindow\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<CHARACTER_LITERAL_1>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "<UNEXPECTED_CHARACTER>",
  };

}
