/* Generated By:JavaCC: Do not edit this line. NSISParserConstants.java */
package uk.co.chamberlain.netbeans.nsis.javacc.lexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NSISParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 4;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int MULTI_LINE_FUNCTION = 9;
  /** RegularExpression Id. */
  int MULTI_LINE_SECTION = 12;
  /** RegularExpression Id. */
  int ABSTRACT = 14;
  /** RegularExpression Id. */
  int ASSERT = 15;
  /** RegularExpression Id. */
  int BOOLEAN = 16;
  /** RegularExpression Id. */
  int BREAK = 17;
  /** RegularExpression Id. */
  int BYTE = 18;
  /** RegularExpression Id. */
  int CASE = 19;
  /** RegularExpression Id. */
  int CATCH = 20;
  /** RegularExpression Id. */
  int CHAR = 21;
  /** RegularExpression Id. */
  int CLASS = 22;
  /** RegularExpression Id. */
  int CONST = 23;
  /** RegularExpression Id. */
  int CONTINUE = 24;
  /** RegularExpression Id. */
  int _DEFAULT = 25;
  /** RegularExpression Id. */
  int DO = 26;
  /** RegularExpression Id. */
  int DOUBLE = 27;
  /** RegularExpression Id. */
  int ELSE = 28;
  /** RegularExpression Id. */
  int ENUM = 29;
  /** RegularExpression Id. */
  int EXTENDS = 30;
  /** RegularExpression Id. */
  int FALSE = 31;
  /** RegularExpression Id. */
  int FINAL = 32;
  /** RegularExpression Id. */
  int FINALLY = 33;
  /** RegularExpression Id. */
  int FLOAT = 34;
  /** RegularExpression Id. */
  int FOR = 35;
  /** RegularExpression Id. */
  int GOTO = 36;
  /** RegularExpression Id. */
  int IF = 37;
  /** RegularExpression Id. */
  int IMPLEMENTS = 38;
  /** RegularExpression Id. */
  int IMPORT = 39;
  /** RegularExpression Id. */
  int INSTANCEOF = 40;
  /** RegularExpression Id. */
  int INT = 41;
  /** RegularExpression Id. */
  int INTERFACE = 42;
  /** RegularExpression Id. */
  int LONG = 43;
  /** RegularExpression Id. */
  int NAME = 44;
  /** RegularExpression Id. */
  int NEW = 45;
  /** RegularExpression Id. */
  int NULL = 46;
  /** RegularExpression Id. */
  int PACKAGE = 47;
  /** RegularExpression Id. */
  int PRIVATE = 48;
  /** RegularExpression Id. */
  int PROTECTED = 49;
  /** RegularExpression Id. */
  int PUBLIC = 50;
  /** RegularExpression Id. */
  int RETURN = 51;
  /** RegularExpression Id. */
  int SHORT = 52;
  /** RegularExpression Id. */
  int STATIC = 53;
  /** RegularExpression Id. */
  int STRICTFP = 54;
  /** RegularExpression Id. */
  int SUPER = 55;
  /** RegularExpression Id. */
  int SWITCH = 56;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 57;
  /** RegularExpression Id. */
  int THIS = 58;
  /** RegularExpression Id. */
  int THROW = 59;
  /** RegularExpression Id. */
  int THROWS = 60;
  /** RegularExpression Id. */
  int TRANSIENT = 61;
  /** RegularExpression Id. */
  int TRUE = 62;
  /** RegularExpression Id. */
  int TRY = 63;
  /** RegularExpression Id. */
  int VOID = 64;
  /** RegularExpression Id. */
  int VOLATILE = 65;
  /** RegularExpression Id. */
  int WHILE = 66;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 67;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 68;
  /** RegularExpression Id. */
  int HEX_LITERAL = 69;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 70;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 71;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 72;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 73;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 74;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 75;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 76;
  /** RegularExpression Id. */
  int STRING_LITERAL = 77;
  /** RegularExpression Id. */
  int IDENTIFIER = 78;
  /** RegularExpression Id. */
  int LETTER = 79;
  /** RegularExpression Id. */
  int PART_LETTER = 80;
  /** RegularExpression Id. */
  int LPAREN = 81;
  /** RegularExpression Id. */
  int RPAREN = 82;
  /** RegularExpression Id. */
  int LBRACE = 83;
  /** RegularExpression Id. */
  int RBRACE = 84;
  /** RegularExpression Id. */
  int LBRACKET = 85;
  /** RegularExpression Id. */
  int RBRACKET = 86;
  /** RegularExpression Id. */
  int COMMA = 87;
  /** RegularExpression Id. */
  int DOT = 88;
  /** RegularExpression Id. */
  int AT = 89;
  /** RegularExpression Id. */
  int ASSIGN = 90;
  /** RegularExpression Id. */
  int LT = 91;
  /** RegularExpression Id. */
  int BANG = 92;
  /** RegularExpression Id. */
  int TILDE = 93;
  /** RegularExpression Id. */
  int HOOK = 94;
  /** RegularExpression Id. */
  int COLON = 95;
  /** RegularExpression Id. */
  int EQ = 96;
  /** RegularExpression Id. */
  int LE = 97;
  /** RegularExpression Id. */
  int GE = 98;
  /** RegularExpression Id. */
  int NE = 99;
  /** RegularExpression Id. */
  int SC_OR = 100;
  /** RegularExpression Id. */
  int SC_AND = 101;
  /** RegularExpression Id. */
  int INCR = 102;
  /** RegularExpression Id. */
  int DECR = 103;
  /** RegularExpression Id. */
  int PLUS = 104;
  /** RegularExpression Id. */
  int MINUS = 105;
  /** RegularExpression Id. */
  int STAR = 106;
  /** RegularExpression Id. */
  int SLASH = 107;
  /** RegularExpression Id. */
  int BIT_AND = 108;
  /** RegularExpression Id. */
  int BIT_OR = 109;
  /** RegularExpression Id. */
  int XOR = 110;
  /** RegularExpression Id. */
  int REM = 111;
  /** RegularExpression Id. */
  int LSHIFT = 112;
  /** RegularExpression Id. */
  int PLUSASSIGN = 113;
  /** RegularExpression Id. */
  int MINUSASSIGN = 114;
  /** RegularExpression Id. */
  int STARASSIGN = 115;
  /** RegularExpression Id. */
  int SLASHASSIGN = 116;
  /** RegularExpression Id. */
  int ANDASSIGN = 117;
  /** RegularExpression Id. */
  int ORASSIGN = 118;
  /** RegularExpression Id. */
  int XORASSIGN = 119;
  /** RegularExpression Id. */
  int REMASSIGN = 120;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 121;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 122;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 123;
  /** RegularExpression Id. */
  int ELLIPSIS = 124;
  /** RegularExpression Id. */
  int UNEXPECTED_CHARACTER = 125;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_FUNCTION = 3;
  /** Lexical state. */
  int IN_MULTI_LINE_SECTION = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<token of kind 2>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 7>",
    "\"FUNCTION\"",
    "\"FUNCTIONEND\"",
    "<token of kind 10>",
    "\"SECTION\"",
    "\"SECTIONEND\"",
    "<token of kind 13>",
    "\"abstract\"",
    "\"assert\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"name\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "<UNEXPECTED_CHARACTER>",
  };

}
